name: e2ee_core
description: "Platform-neutral E2EE protocol and note state engine."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.0
  flutter: ">=1.17.0"

dependencies:
  cryptography: ^2.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  path: ^1.9.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
