import 'dart:io';

import 'package:e2ee_notes/vault/read_or_create_random_bytes.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

void main() {
  late Directory directory;
  late File file;

  setUp(() async {
    directory = await Directory.systemTemp.createTemp('e2ee-random-bytes-');
    file = File(p.join(directory.path, 'bytes.bin'));
  });

  tearDown(() => directory.delete(recursive: true));

  test('persists generated bytes and reuses them on reopening', () async {
    final bytes = await readOrCreateRandomBytes(file, 32);
    expect(bytes, hasLength(32));
    expect(await file.readAsBytes(), bytes);
    expect(await readOrCreateRandomBytes(file, 32), bytes);
  });

  test('rejects an unexpected length without overwriting the file', () async {
    await file.writeAsBytes([1, 2, 3]);
    await expectLater(
      readOrCreateRandomBytes(file, 32),
      throwsA(
        isA<FormatException>().having(
          (error) => error.message,
          'message',
          'Expected 32 bytes, found 3',
        ),
      ),
    );
    expect(await file.readAsBytes(), [1, 2, 3]);
  });
}
