name: hardware_keys
description: "Federated hardware-backed recipient key API for E2EE Notes."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.yozen.hardware_keys
        pluginClass: HardwareKeysPlugin
      ios:
        pluginClass: HardwareKeysPlugin
      linux:
        pluginClass: HardwareKeysPlugin
      macos:
        pluginClass: HardwareKeysPlugin
      windows:
        pluginClass: HardwareKeysPluginCApi
