name: secure_keys
description: "Key capability interfaces and native key adapters."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.yozen.secure_keys
        pluginClass: SecureKeysPlugin
      ios:
        pluginClass: SecureKeysPlugin
      linux:
        pluginClass: SecureKeysPlugin
      macos:
        pluginClass: SecureKeysPlugin
      windows:
        pluginClass: SecureKeysPluginCApi
