name: e2ee_notes
description: "Storage-independent end-to-end encrypted notes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  path: ^1.9.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  e2ee_core:
    path: ../packages/e2ee_core
  hardware_keys:
    path: ../packages/hardware_keys
  notes_repository:
    path: ../packages/notes_repository
  path_provider: ^2.1.5
  storage_api:
    path: ../packages/storage_api
  storage_filesystem:
    path: ../packages/storage_filesystem

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
