name: storage_filesystem
description: "Filesystem implementation of the E2EE opaque storage contract."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: ">=1.17.0"

dependencies:
  path: ^1.9.1
  flutter:
    sdk: flutter
  storage_api:
    path: ../storage_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
